root: true
extends:
  - airbnb
  - prettier
env:
  node: true
  es6: true
  jest: true
rules:
  "no-console": off
  "no-underscore-dangle": off
  "react/jsx-filename-extension":
    - error
    - extensions:
      - ".js"
      - ".jsx"
  "prettier/prettier":
    - error
    - singleQuote: true
      semi: true
  "flowtype-errors/show-errors": error
  "flowtype-errors/show-warnings": warn
plugins:
  - import
  - prettier
  - flowtype
  - "flowtype-errors"
settings:
  "import/resolve":
    moduleDirectory:
      - node_modules
parser: "babel-eslint"
parserOptions:
  sourceType: module
